# Generated by Django 5.2 on 2025-05-09 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_category_name'),
        ('users', '0002_alter_payment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_payments', to='content.content', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_subscriptions', to='content.content', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
